[package]
name = "async-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
reqwest = {version ="0.12.4", features = ["blocking","json"]}
tokio = {version = "1.37.0", features=["full"]}
